name: dmlib_env

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-image
  - pillow
  - h5py
  - pyqt
  - dataclasses
  - setuptools
  - wheel
  - cython
  - git
  - pip
  - pip:
    - PyQt5
