name: dmlib_env

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.6
  - numpy
  - scipy=1.5.2
  - matplotlib
  - pandas=1.1.5
  - scikit-image
  - pillow=8.3.2
  - h5py
  - pyqt=5.9.2
  - dataclasses
  - setuptools
  - wheel
  - cython
  - git
  - pip
  - pip:
    - PyQt5==5.9.2
